* 使用Emacs配置web开发环境

** 初衷

Emacs的教程比较多，如果你熟练使用google，基本一搜一大堆。这里我不介绍emcas基本的使用方法，而是说说如果使用emacs做web开发。

事实上，很少人会使用emacs做web开发，尤其是国内，emacs更多的是用在linux开发上面，如果你是纯做web开发的，建议还是直接使用vscode等开箱即用的工具。

但如果你喜欢在一个终端应付不同的工作环境，emcas确实是一个不错的选择。在emacs圈子里，大多数人不只用emacs做开发工作，他被称为"神之编辑器"，相比于vim"编辑器之神"，他似乎更加让人感觉牛逼一些。

我们常说emacs是一个伪装成编辑器的"操作系统"，原因是它的功能已经远远超越了编辑器的范畴，他可以写文档，记笔记，看图片，看视频，发邮件，各种语言编程，登录电报聊天等等。。

几乎所有东西都可以做，对于喜欢将多端东西集成于一点的玩家来说简直是不二选择。并且，学习Emacs可以让自己更加熟悉操作系统，终端等。

而对于我来说，emcas可以提升我的开发效率，丰富的快键键，简单的项目管理，无敌的模糊搜索功能，简直让开发体验飞上了天。

我是一名web前端开发人员，机缘巧合碰到同事在用Emacs，这里就按照web的要求，配置了一套emacs的前端开发配置。

如果Emcas你还没有接触过，你可以先看一些Emacs基础的教程，他的学习成本是相对高一点，但是物超所值，当真正上手之后，开发效率会上升一个层次，里给出以下Emacs的学习地址

[[https://www.gnu.org/software/emacs/][官网]]

[[https://emacs-china.org/][emacs-china]]

[[https://cestlaz.github.io/post/using-emacs-74-eglot/][Mike Zamansky Using Emacs]]

: 还有b站的一些视频学习资料，大家可以自己去搜一搜，刚刚接触emcas我建议还是多看一些视频资料，看看基础的用法。

*** Web 配置(基础配置可以参考我的配置 [[https://github.com/petsgre/emacs-config][https://github.com/petsgre/emacs-config]] )

下面我会为大家介绍web相关的配置

[[https:melpa.org][melpa.org]] 是Emacs的一个资源托管平台，类似于atm,npm这类东西

*常用mode*

| mode     | 作用       | 链接                                |
|----------+------------+-------------------------------------|
| flycheck | eslint检查 | https://www.flycheck.org/en/latest/ |

*** 测试标题

#+BEGIN_QUOTE
到底会不会有前置空间
#+END_QUOTE    

#+BEGIN_SRC js
  const a = 1
  var asd = 2
  return a + asd
#+END_SRC

#+RESULTS:
: 3

